<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmfZidb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmfZidb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmfZidb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmfZidb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGmfZidb\App_KernelDevDebugContainer([
    'container.build_hash' => 'GmfZidb',
    'container.build_id' => 'd6b2cbf0',
    'container.build_time' => 1685648840,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmfZidb');
